---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-ast
            exclude: \{\{cookiecutter.project_slug\}\}
          - id: check-case-conflict
          - id: check-yaml
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          - id: end-of-file-fixer
          - id: file-contents-sorter
            files: .*\.in$
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: no-commit-to-branch
            args: [--branch, master]
          - id: pretty-format-json
            args: [--no-sort-keys, --autofix]
            files: cookiecutter.json
          - id: pretty-format-json
            args: [--autofix]
            exclude: cookiecutter.json
          - id: trailing-whitespace

    - repo: https://github.com/codespell-project/codespell
      rev: v2.2.6
      hooks:
          - id: codespell

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.35.1
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt

    - repo: https://github.com/rstcheck/rstcheck
      rev: v6.2.0
      hooks:
          - id: rstcheck
            exclude: /?docs/

    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.5.5
      hooks:
          - id: forbid-tabs
            exclude: (Makefile|make\.bat)
