name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Python Tox on Fedora
        uses: fedora-python/tox-github-action@v0.4
        with:
          # Tox environment to run the tests on
          tox_env: py39
  
